name: 'Security Action'
description: 'Collect and Generalize multiple CI Security checks'
inputs:
# in-name:
#   description: yadda yadda
#   required: true
#   default: 0
  github_token:
    description: |
      Secret token to push review comments, and
      interact with the repository systematically
    required: true
  slack_token:
    description: |
      Secret token to forward findings to slack
    required: false
  assignees:
    description: assign PR to the people linked
    default: |
      thypon
      bcaller
  debug:
    description: enables debug output for this action
    required: false
  codeql_config:
    description: CodeQL configuration config config
    default: ./.github/codeql/codeql-config.yml
# outputs:
#   out-name:
#     description: yadda yadda
#     value: ${{ steps.output-step-id.outputs.output-name }}
runs:
  using: 'composite'
  steps:
    - name: Install Brakeman
      id: install-brakeman
      shell: bash
      run: |
        set -xe
        GEM_HOME=../.gem gem install bundler
        ../.gem/bin/bundle install
    - name: Brakeman
      id: brakeman
      shell: bash
      run: |
        set -xe
        ../.gem/bin/bundler exec brakeman --quiet -o brakeman.sarif --no-exit-on-warn --no-exit-on-error --force ./
        cat brakeman.sarif
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: brakeman.sarif